filter:
    paths:
        - 'src/*'
        - 'tests/*'

tools:
    php_code_sniffer:
        config:
            standard: PSR2

build:
  nodes:
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=clover.xml
            coverage:
              file: clover.xml
              format: clover