filter:
    paths:
        - 'src/*'
        - 'tests/*'

tools:
    php_cs_fixer:
        config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1

build:
  nodes:
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=clover.xml
            coverage:
              file: clover.xml
              format: clover
