<?php
/**
 * Copyright (c) 2019 - present
 * updown - CheckTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 15/2/2019
 * MIT license: https://github.com/biscolab/updown-php/blob/master/LICENSE
 */

namespace Tests\Unit;

use Biscolab\UpDown\Fields\CheckFields;
use Biscolab\UpDown\Fields\SslFields;
use Biscolab\UpDown\Objects\Check;
use Biscolab\UpDown\Tests\TestCase;

class CheckTest extends TestCase
{

    /**
     * @var Check
     */
    protected $check;

    /**
     * @test
     */
    public function testSetCheck()
    {

        $this->assertEquals($this->check->{CheckFields::URL}, "https://updown.io");
        $this->assertEquals($this->check->{CheckFields::LAST_STATUS}, 200);
        $this->assertEquals($this->check->{CheckFields::FAVICON_URL}, "https://updown.io/favicon.png");
        $this->assertEquals($this->check->{CheckFields::HTTP_VERB}, "GET/HEAD");
        $this->assertEquals($this->check->{CheckFields::SSL}->{SslFields::TESTED_AT},
            strtotime("2016-02-07T13:30:08Z"));

    }

    /**
     * @test
     */
    public function testGetId()
    {

        $this->assertEquals($this->check->getId(), "ngg8");

    }

    /**
     * @test
     */
    public function testDateTimeFields()
    {

        $this->assertEquals("2016", date('Y', $this->check->{CheckFields::NEXT_CHECK_AT}));

    }

    /**
     * Setup the test environment.
     */
    protected function setUp()
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $data = [
            "token"              => "ngg8",
            "url"                => "https://updown.io",
            "alias"              => "",
            "last_status"        => 200,
            "uptime"             => 99.954,
            "down"               => false,
            "down_since"         => null,
            "error"              => null,
            "period"             => 30,
            "apdex_t"            => 0.25,
            "string_match"       => "",
            "enabled"            => true,
            "published"          => true,
            "disabled_locations" => [],
            "last_check_at"      => "2016-02-07T13:16:07Z",
            "next_check_at"      => "2016-02-07T13:16:37Z",
            "mute_until"         => null,
            "favicon_url"        => "https://updown.io/favicon.png",
            "custom_headers"     => [],
            "http_verb"          => "GET/HEAD",
            "http_body"          => null,
            "ssl"                => [
                "tested_at" => "2016-02-07T13:30:08Z",
                "valid"     => true,
                "error"     => null
            ]
        ];

        $this->check->setData($data);
    }
}